=== Acierrenc3/DAW/1ERO/LND/T4/Ejercicio 5/T4_Ejerc5.2/ikea.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1" xml:lang="es">
    <xs:element name="Ikea_Tenerife">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="proveedores" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nro_pro" type="xs:positiveInteger"></xs:element>
                        <xs:element name="nom_p" type="xs:string"></xs:element>
                        <xs:element name="categoria" type="xs:string"></xs:element>
                        <xs:element name="ciudad_p" type="xs:string"></xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="items" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nro_i" type="xs:positiveInteger"></xs:element>
                        <xs:element name="descripcion_i" type="xs:string"></xs:element>
                        <xs:element name="ciudad_i" type="xs:string"></xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="pedidos" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nro_pe" type="xs:positiveInteger"></xs:element>
                        <xs:element name="nro_c" type="xs:positiveInteger"></xs:element>
                        <xs:element name="nro_i" type="xs:positiveInteger"></xs:element>
                        <xs:element name="nro_pro" type="xs:positiveInteger"></xs:element>
                        <xs:element name="cantidad" type="xs:positiveInteger"></xs:element>
                        <xs:element name="precio" type="xs:positiveInteger"></xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="clientes" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nro_c" type="xs:positiveInteger"></xs:element>
                        <xs:element name="nom_c" type="xs:string"></xs:element>
                        <xs:element name="ciudad_c" type="xs:string"></xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    </xs:element>
</xs:schema>

=== Acierrenc3/DAW/1ERO/LND/T4/Ejercicio 5/T4_Ejerc5.2/T4_Ejerc5.2.xml
<?xml version="1.0" encoding="UTF-8"?>
<Ikea_Tenerife xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ikea.xsd">
    <!--PROVEEDORES-->
    <proveedores>
        <nro_pro>078</nro_pro>
        <nom_p>Maderas John</nom_p>
        <categoria>Materias Primas</categoria>
        <ciudad_p>California, EEUU</ciudad_p>
    </proveedores>
    <proveedores>
        <nro_pro>027</nro_pro>
        <nom_p>Metales Tom</nom_p>
        <categoria>Materias Primas</categoria>
        <ciudad_p>Alaska, EEUU</ciudad_p>
    </proveedores>
    <!--ITEMS-->
    <items>
        <nro_i>775</nro_i>
        <descripcion_i>Madera de Abeto</descripcion_i>
        <ciudad_i>California, EEUU</ciudad_i>
    </items>
    <items>
        <nro_i>78</nro_i>
        <descripcion_i>Tornillos 38mm</descripcion_i>
        <ciudad_i>Alaska, EEUU</ciudad_i>
    </items>
    <!--PEDIDOS-->
    <pedidos>
        <nro_pe>12748</nro_pe>
        <nro_c>4567</nro_c>
        <nro_i>775</nro_i>
        <nro_pro>078</nro_pro>
        <cantidad>100</cantidad>
        <precio>10000</precio>
    </pedidos>
    <pedidos>
        <nro_pe>12749</nro_pe>
        <nro_c>127</nro_c>
        <nro_i>78</nro_i>
        <nro_pro>027</nro_pro>
        <cantidad>1500</cantidad>
        <precio>500</precio>
    </pedidos>
    <!--CLIENTES-->
    <clientes>
        <nro_c>4567</nro_c>
        <nom_c>Marcelo Bielsa</nom_c>
        <ciudad_c>California, EEUU</ciudad_c>
    </clientes>
    <clientes>
        <nro_c>127</nro_c>
        <nom_c>Francesco Totti</nom_c>
        <ciudad_c>Alaska, EEUU</ciudad_c>
    </clientes>
</Ikea_Tenerife>
