=== Acierrenc3/DAW/1ERO/LND/EjerciciosXML/HechosHistoricos/hechoshistoricos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="0.1" xml:lang="es">
    <xs:element name="hechos_historicos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="hecho" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="fecha" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="dia" minOccurs="1" maxOccurs="unbounded" type="xs:integer"/>
                                        <xs:element name="mes" minOccurs="1" maxOccurs="unbounded" type="xs:integer"/>
                                        <xs:element name="anio" minOccurs="1" maxOccurs="unbounded" type="xs:integer"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="descripcion"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Acierrenc3/DAW/1ERO/LND/EjerciciosXML/HechosHistoricos/hechoshistoricos.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="hechoshistoricos.xsl"?>
<hechos_historicos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="hechoshistoricos.xsd">
<hecho descripcion="IBM da a conocer el PC.">
    <fecha>
        <dia>12</dia>
        <mes>8</mes>
        <anio>1981</anio>
    </fecha>
</hecho>
<hecho descripcion="Se funda Google.">
    <fecha>
        <dia>4</dia>
        <mes>9</mes>
        <anio>1998</anio>
    </fecha>
</hecho>
<hecho descripcion="Se funda Facebook.">
    <fecha>
        <dia>4</dia>
        <mes>2</mes>
        <anio>2004</anio>
    </fecha>
</hecho>
</hechos_historicos>
