=== Acierrenc3/DAW/LND/EjerciciosXML/cds.dtd
<!ELEMENT cds (cd*)>
<!ELEMENT cd (titulo*,artista*,pais*,discografica*,precio*,anio*)>

<!-- TITULOS -->
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT artista (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT discografica (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT anio (#PCDATA)>

=== Acierrenc3/DAW/1ERO/LND/EjerciciosXML/cds.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cds SYSTEM "cds.dtd">
<cds>
    <cd>
        <titulo></titulo>
        <artista></artista>
        <pais></pais>
        <discografica></discografica>
        <precio></precio>
        <anio></anio>
    </cd>
    <cd>
        <titulo></titulo>
        <artista></artista>
        <pais></pais>
        <discografica></discografica>
        <precio></precio>
        <anio></anio>
    </cd>
    <cd>
        <titulo></titulo>
        <artista></artista>
        <pais></pais>
        <discografica></discografica>
        <precio></precio>
        <anio></anio>
    </cd>
</cds>
