=== Acierrenc3/DAW/LND/T4/Ejercicio 5/T4_Ejerc5.1/basedatos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1" xml:lang="es">
    <xs:element name="basededatos"></xs:element>
    <xs:complexType name="piezas">
        <xs:sequence>
            <xs:element name="piezas" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="pieza" type="xs:string"></xs:element>
                        <xs:element name="codigo" type="xs:integer"></xs:element>
                        <xs:element name="nombre" type="xs:string"></xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="proveedores">
        <xs:sequence>
            <xs:element name="proveedores" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="proveedor" type="xs:string"></xs:element>
                        <xs:element name="id" type="xs:integer"></xs:element>
                        <xs:element name="proveedor" type="xs:string"></xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="suministros">
        <xs:sequence>
            <xs:element name="suministros" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>   
                        <xs:element name="suministro" type="xs:string"></xs:element>
                        <xs:element name="codigo_pieza" type="xs:integer"></xs:element>
                        <xs:element name="idProveedor" type="xs:integer"></xs:element>
                        <xs:element name="precio" type="xs:integer"></xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Acierrenc3/DAW/1ERO/LND/T4/T4_Ejerc5/T4_Ejerc5.1/T4_Ejerc5.1.xml
<?xml version="1.0" encoding="UTF-8"?>
<basededatos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="basedatos.xsd">
    <!--PIEZAS-->
    <piezas>
        <pieza>Modular</pieza>
        <codigo>78</codigo>
        <nombre>Resorte Conico</nombre>
    </piezas>
    <piezas>
        <pieza>Central</pieza>
        <codigo>03</codigo>
        <nombre>Encendedor Motor</nombre>
    </piezas>
    <!--PROVEEDORES-->
    <proveedores>
        <proveedor>Hyundai</proveedor>
        <id>308</id>
        <nombre2>Hyundai Motors</nombre2>
    </proveedores>
    <proveedores>
        <proveedor>Renault</proveedor>
        <id>002</id>
        <nombre2>Casa Renault</nombre2>
    </proveedores>
    <!--SUMINISTROS-->
    <suministros>
        <suministro>Si</suministro>
        <codigo_pieza>03</codigo_pieza>
        <idProveedor>308</idProveedor>
        <precio moneda="EUR">465</precio>
    </suministros>
    <suministros>
        <suministro>Si</suministro>
        <codigo_pieza>78</codigo_pieza>
        <idProveedor>002</idProveedor>
        <precio moneda="EUR">320</precio>
    </suministros>
</basededatos>
