=== Acierrenc3/DAW/LND/EjerciciosXML/TablaPersona/tabla.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="0.1" xml:lang="es">
    <xs:element name="personas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="fechas">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="fecha" minOccurs="1" maxOccurs="unbounded" type="xs:string"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="persona" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="incomes" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="income" type="xs:integer" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="outcomes" minOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="outcome" maxOccurs="unbounded" minOccurs="1" type="xs:integer"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                            <xs:attribute name="nombre" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Acierrenc3/DAW/LND/EjerciciosXML/TablaPersona/tabla.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="tabla.xsl"?>
<personas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="tabla.xsd">
    <fechas>
        <fecha>20/07/15</fecha>
        <fecha>28/07</fecha>
        <fecha>09/08</fecha>
        <fecha>22/08</fecha>
        <fecha>25/08</fecha>
    </fechas>
    <persona nombre="Anthony">
        <incomes>
            <income>200</income>
            <income>0</income>
            <income>0</income>
            <income>40</income>
            <income>0</income>
        </incomes>
        <outcomes>
            <outcome>50</outcome>
            <outcome>100</outcome>
            <outcome>50</outcome>
            <outcome>0</outcome>
            <outcome>20</outcome>
        </outcomes>
    </persona>
    <persona nombre="Lionel">
        <incomes>
            <income>0</income>
            <income>100</income>
            <income>0</income>
            <income>0</income>
            <income>0</income>
        </incomes>
        <outcomes>
            <outcome>0</outcome>
            <outcome>0</outcome>
            <outcome>80</outcome>
            <outcome>110</outcome>
            <outcome>0</outcome>
        </outcomes>
    </persona>
</personas>
