=== Acierrenc3/DAW/1ERO/LND/T4/Ejercicios 1_4/T4_Ejerc1/basededatos.dtd
<!ELEMENT basededatos (piezas*, proveedores*, suministros*) >
<!ELEMENT piezas (pieza+, codigo+, nombre*)>
<!ELEMENT proveedores (proveedor+, id+, nombre2*)>
<!ELEMENT suministros (suministro, codigo_pieza+, idProveedor+, precio)>

<!ELEMENT pieza (#PCDATA)>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT proveedor (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT nombre2 (#PCDATA)>
<!ELEMENT suministro (#PCDATA)>
<!ELEMENT codigo_pieza (#PCDATA)>
<!ELEMENT idProveedor (#PCDATA)>
<!ELEMENT precio (#PCDATA)>

<!ATTLIST precio moneda CDATA #REQUIRED >

=== Acierrenc3/DAW/LND/T4/Ejercicios 1_4/T4_Ejerc1/T4_Ejerc1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE basededatos SYSTEM "basededatos.dtd">
<basededatos>
    <!--PIEZAS-->
    <piezas>
        <pieza>Modular</pieza>
        <codigo>B78</codigo>
        <nombre>Resorte Conico</nombre>
    </piezas>
    <piezas>
        <pieza>Central</pieza>
        <codigo>A03</codigo>
        <nombre>Encendedor Motor</nombre>
    </piezas>
    <!--PROVEEDORES-->
    <proveedores>
        <proveedor>Hyundai</proveedor>
        <id>P308</id>
        <nombre2>Hyundai Motors</nombre2>
    </proveedores>
    <proveedores>
        <proveedor>Renault</proveedor>
        <id>P002</id>
        <nombre2>Casa Renault</nombre2>
    </proveedores>
    <!--SUMINISTROS-->
    <suministros>
        <suministro>Si</suministro>
        <codigo_pieza>A03</codigo_pieza>
        <idProveedor>P308</idProveedor>
        <precio moneda="EUR">465</precio>
    </suministros>
    <suministros>
        <suministro>Si</suministro>
        <codigo_pieza>B78</codigo_pieza>
        <idProveedor>P002</idProveedor>
        <precio moneda="EUR">320</precio>
    </suministros>
</basededatos>
