=== Acierrenc3/DAW/1ERO/LND/T4/Ejercicio 5/T4_Ejerc5.4/hospitales.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1" xml:lang="es">
    <xs:element name="Hospitales">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Hospital" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"></xs:element>
                            <xs:element name="direccion" type="xs:string"></xs:element>
                            <xs:element name="telefono" type="xs:integer"></xs:element>
                            <xs:element name="num_camas" type="xs:string"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Sala" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="hospital_cod" type="xs:integer"></xs:element>
                            <xs:element name="sala_cod" type="xs:integer"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Plantilla" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="hospital_cod" type="xs:integer"></xs:element>
                            <xs:element name="sala_cod" type="xs:integer"></xs:element>
                            <xs:element name="empleado_num" type="xs:integer"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Ocupacion" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="inscripcion" type="xs:string"></xs:element>
                            <xs:element name="hospital_cod" type="xs:integer"></xs:element>
                            <xs:element name="sala_cod" type="xs:integer"></xs:element>
                            <xs:element name="cama" type="xs:integer"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Doctor" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="hospital_cod" type="xs:integer"></xs:element>
                            <xs:element name="doctor_num" type="xs:integer"></xs:element>
                            <xs:element name="apellido" type="xs:string"></xs:element>
                            <xs:element name="especialidad" type="xs:string"></xs:element>
                        </xs:sequence>
                    </xs:complexType>                  
                </xs:element>
                <xs:element name="Enfermo" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="inscripcion" type="xs:date"></xs:element>
                            <xs:element name="apellido" type="xs:string"></xs:element>
                            <xs:element name="direccion" type="xs:string"></xs:element>
                            <xs:element name="s"></xs:element>
                            <xs:element name="nss" type="xs:string"></xs:element>
                        </xs:sequence>
                    </xs:complexType>                  
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Acierrenc3/DAW/1ERO/LND/T4/Ejercicio 5/T4_Ejerc5.4/T4_Ejerc5.4.xml
<?xml version="1.0" encoding="UTF-8"?>
<Hospitales xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="hospitales.xsd">
    <!--HOSPITALES-->
    <Hospital>
        <nombre>La Candelaria</nombre>
        <direccion>Calle Candelaria, 37 , Santa Cruz de Tenerife</direccion>
        <telefono>922354578</telefono>
        <num_camas>30000</num_camas>
    </Hospital>
    <Hospital>
        <nombre>San Diego</nombre>
        <direccion>Calle Buenaventura, Las Palmas de Gran Canaria</direccion>
        <telefono>928456789</telefono>
        <num_camas>25000</num_camas>
    </Hospital>
    <!--SALAS-->
    <Sala>
        <hospital_cod>38</hospital_cod>
        <sala_cod>15</sala_cod>
    </Sala>
    <Sala>
        <hospital_cod>15</hospital_cod>
        <sala_cod>38</sala_cod>
    </Sala>
    <!--PLANTILLAS-->
    <Plantilla>
        <hospital_cod>38</hospital_cod>
        <sala_cod>15</sala_cod>
        <empleado_num>247</empleado_num>
    </Plantilla>
    <Plantilla>
        <hospital_cod>15</hospital_cod>
        <sala_cod>38</sala_cod>
        <empleado_num>127</empleado_num>
    </Plantilla>
    <!--OCUPACIONES-->
    <Ocupacion>
        <inscripcion>Si</inscripcion>
        <hospital_cod>38</hospital_cod>
        <sala_cod>15</sala_cod>
        <cama>27</cama>
    </Ocupacion>
    <Ocupacion>
        <inscripcion>Si</inscripcion>
        <hospital_cod>15</hospital_cod>
        <sala_cod>38</sala_cod>
        <cama>144</cama>
    </Ocupacion>
    <!--DOCTORES-->
    <Doctor>
        <hospital_cod>38</hospital_cod>
        <doctor_num>247</doctor_num>
        <apellido>Esteban Perez</apellido>
        <especialidad>Paliativos</especialidad>
    </Doctor>
    <Doctor>
        <hospital_cod>15</hospital_cod>
        <doctor_num>127</doctor_num>
        <apellido>Gomez Ventura</apellido>
        <especialidad>Medico Familia</especialidad>
    </Doctor>
    <!--ENFERMOS-->
    <Enfermo>
        <inscripcion>2022-06-06</inscripcion>
        <apellido>Perez</apellido>
        <direccion>Avenida La Salle, 12</direccion>
        <s></s>
        <nss>3845674AFS</nss>
    </Enfermo>
    <Enfermo>
        <inscripcion>2019-05-04</inscripcion>
        <apellido>Rodriguez Lopez</apellido>
        <direccion>Calle Triana, 38</direccion>
        <s></s>
        <nss>48785682AFS</nss>
    </Enfermo>
</Hospitales>
