=== Acierrenc3/DAW/1ERO/LND/EjerciciosXML/Basicocd/basicocd.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="0.1" xml:lang="es">
    <xs:element name="CD_OFERTA">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="CD" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="artista" type="xs:string"/>
                            <xs:element name="pais" type="xs:string"/>
                            <xs:element name="discografica" type="xs:string"/>
                            <xs:element name="precio" type="xs:decimal"/>
                            <xs:element name="Año" type="año"/>
                        </xs:sequence>
                            <xs:attribute name="titulo"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
        <xs:simpleType name="año">
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="1900"/>
                <xs:maxInclusive value="2023"/>
                <xs:pattern value="[0-9]{4}"></xs:pattern>
            </xs:restriction>
        </xs:simpleType>
</xs:schema>

=== Acierrenc3/DAW/LND/EjerciciosXML/Basicocd/basicocd.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="basicocd.xsl"?>
<CD_OFERTA xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="basicocd.xsd">
    <CD titulo="Still got the blues">
        <artista>Gary Moore</artista>
        <pais>UK</pais>
        <discografica>Virgin Records</discografica>
        <precio>10.20</precio>
        <Año>1990</Año>
    </CD>
    <CD titulo="One night only">
        <artista>Bee Gees</artista>
        <pais>UK</pais>
        <discografica>Polydor</discografica>
        <precio>10.90</precio>
        <Año>1998</Año>
    </CD>
    <CD titulo="When a man loves a woman">
        <artista>Percy Sledge</artista>
        <pais>USA</pais>
        <discografica>Atlantic</discografica>
        <precio>8.70</precio>
        <Año>1987</Año>
    </CD>
    <CD titulo="Big Willie style">
        <artista>Will Smith</artista>
        <pais>USA</pais>
        <discografica>Columbia</discografica>
        <precio>9.90</precio>
        <Año>1997</Año>
    </CD>
    <CD titulo="La cancion de Juan Perro">
        <artista>Radio Futura</artista>
        <pais>España</pais>
        <discografica>Sony Music-Ariola</discografica>
        <precio>9.90</precio>
        <Año>1987</Año>
    </CD>
    <CD titulo="The dock of the bay">
        <artista>Otis Redding</artista>
        <pais>USA</pais>
        <discografica>Atlantic</discografica>
        <precio>7.90</precio>
        <Año>1987</Año>
    </CD>
</CD_OFERTA>
