=== Acierrenc3/DAW/LND/EjerciciosXML/Paises/paises.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="0.1" xml:lang="es">
    <xs:element name="ciudades">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ciudad" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" minOccurs="1" maxOccurs="unbounded" type="xs:string"/>
                            <xs:element name="pais" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="continente" type="xs:string" use="required"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="poblacion" minOccurs="1" maxOccurs="unbounded" type="xs:integer"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element> 
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Acierrenc3/DAW/1ERO/LND/EjerciciosXML/Paises/paises.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="paises.xsl"?>
<ciudades xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="paises.xsd">
    <ciudad>
        <nombre>Nueva Delhi</nombre>
        <pais continente="Ásia">India</pais>
        <poblacion>1410000</poblacion>
    </ciudad>
    <ciudad>
        <nombre>Lisboa</nombre>
        <pais continente="Europa">Portugal</pais>
        <poblacion>504718</poblacion>
    </ciudad>
    <ciudad>
        <nombre>El Cairo</nombre>
        <pais continente="África">Egipto</pais>
        <poblacion>9540000</poblacion>
    </ciudad>
</ciudades>
