=== Acierrenc3/DAW/1ERO/LND/EjerciciosXML/XSD/EjFactura/Factura.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1" xml:lang="es">
    <xs:element name="facturas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="factura">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="empresa" type="xs:string"></xs:element>
                            <xs:element name="direccion" type="xs:string"></xs:element>
                            <xs:element name="cif" type="xs:string"></xs:element>
                            <xs:element name="telefono" type="xs:integer"></xs:element>
                            <xs:element name="fax" type="xs:integer"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="clientes">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ncliente" type="xs:integer"></xs:element>
                            <xs:element name="nombre" type="xs:string"></xs:element>
                            <xs:element name="direccionenvio" type="xs:string"></xs:element>
                            <xs:element name="poblacion" type="xs:string"></xs:element>
                            <xs:element name="cod.postal" type="xs:integer"></xs:element>
                            <xs:element name="provincia" type="xs:string"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="pedido">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="fecha" type="xs:date"></xs:element>
                            <xs:element name="npedido" type="xs:integer"></xs:element>
                            <xs:element name="formaDePago" type="formapago"></xs:element>
                            <xs:element name="productos">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="producto" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="referencia" type="xs:string"></xs:element>
                                                    <xs:element name="descripcion" type="xs:string"></xs:element>
                                                    <xs:element name="cantidad" type="xs:integer"></xs:element>
                                                    <xs:element name="precio" type="xs:decimal"></xs:element>
                                                    <xs:element name="iva" type="tipoiva"></xs:element>
                                                    <xs:element name="importe" type="xs:decimal"></xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="totalfactura" type="xs:decimal"></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element> <!--xs:restriction y el pattern van fuera del Ãºltimo element-->
    <xs:simpleType name="formapago">
        <xs:restriction base="xs:string">
            <xs:pattern value="EFECTIVO|TARJETA|TRANSFERENCIA"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="tipoiva">
        <xs:restriction base="xs:string">
            <xs:pattern value="16"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Acierrenc3/DAW/1ERO/LND/EjerciciosXML/XSD/EjFactura/Factura.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="Factura.xsl"?>
<facturas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Factura.xsd">    
    <factura>
        <empresa>Equipos Digitales S.L.</empresa>
        <direccion>Av. Valladolid madrid 28015</direccion>
        <cif>q-9876543</cif>
        <telefono>917776688</telefono>
        <fax>917776699</fax>
    </factura>
    <clientes>
        <ncliente>879</ncliente>
        <nombre>Dario Bueno Gutierrez</nombre>
        <direccionenvio>Av.Oporto nยบ7 4d</direccionenvio>
        <poblacion>Madrid</poblacion>
        <cod.postal>28043</cod.postal>
        <provincia>Madrid</provincia>
    </clientes>
    <pedido>
        <fecha>2022-09-24</fecha>
        <npedido>731</npedido>
        <formaDePago>TARJETA</formaDePago>
        <productos>
            <producto>
                <referencia>M!!</referencia>
                <descripcion>Micro prentium 2</descripcion>
                <cantidad>1</cantidad>
                <precio>230</precio>
                <iva>16</iva>
                <importe>260.80</importe>
            </producto>
        <totalfactura>266.80</totalfactura>  
        </productos>
    </pedido>
</facturas>
